// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace erp_project.Entities.Tables
{
    [Table("Upload", Schema = "Resource")]
    public partial class Upload
    {
        [Key]
        [Column("name")]
        [StringLength(13)]
        public string Name { get; set; }
        [Required]
        [Column("type")]
        [StringLength(30)]
        public string Type { get; set; }
        [Column("userID")]
        public Guid UserId { get; set; }
        [Required]
        [StringLength(50)]
        public string Path { get; set; }
        [Required]
        [Column("fullPath")]
        [StringLength(255)]
        public string FullPath { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }
        [Required]
        [Column("newName")]
        [StringLength(100)]
        public string NewName { get; set; }
        [Required]
        [Column("originalName")]
        [StringLength(100)]
        public string OriginalName { get; set; }
    }
}