// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace erp_project.Entities.Tables
{
    public partial class Upload
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public Guid UserId { get; set; }
        public string Path { get; set; }
        public string FullPath { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}